name: Task
description: Small, actionable task (often created from a parent issue)
title: "[Task]: "
labels: ["task"]

body:
  - type: textarea
    id: summary
    attributes:
      label: What needs to be done?
      placeholder: Brief, action-oriented description
    validations:
      required: true

  - type: input
    id: parent
    attributes:
      label: Parent issue (optional)
      placeholder: "#123"
